### ISSUE TITLE
Validation tool for message specifications

### ISSUE THREAD

**Issue by treiher** [Componolit/RecordFlux-specifications#7]
Correctly verified message specifications are not sufficient, as such specification can still turn out to be invalid in practice (e.g., by misinterpreted descriptions in English prose). A test tool should be created which validates that specified messages are correctly parsed (and serialized). The tool should take a specification and a set of known valid and invalid messages as input and should check, if all messages are correctly classified as valid or invalid. The basis for the tool should be PyRFLX. There is already a very small number of test files available for Ethernet and IPv4 in `tests.data.captured` which could be used for the beginning. For a larger test HTTP/2 should be used (#3).

### Tasks

- [x] Create validation tool `tools/validate_spec.py`
  - Input: specification file, message identifier, directory for valid messages (optional), directory for invalid messages (optional))
  - Output: return value, list of failed validations (message identifier, test file, error message) on stdout, detailed output in JSON file (optional)
- [x] Add existing test data from RecordFlux to `test/data`
- [x] Extend test in `tests/test_spec.py` by call of validation tool (in a generic way, i.e. it should not be necessary to add invocations for new specifications or test data of the validation tool manually)
